spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vault
    username: vault
    password: vault
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: warn
